# Generated by Django 5.2.1 on 2025-08-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='driving_test.question')),
            ],
            options={
                'verbose_name_plural': 'Question Analytics',
            },
        ),
    ]
