# Generated by Django 5.2.1 on 2025-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_test', '0002_testanswer_points_earned_questionanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='test_sessions', to='driving_test.question'),
        ),
    ]
